language: node_js
cache: yarn
after_script:
- npm run codecov
sudo: false
addons:
  ssh_known_hosts: design.optimizely.com
before_deploy:
- rm -rfv dist
- npm run build
deploy:
- provider: npm
  skip_cleanup: true
  api_key:
    secure: g4CaeOUkpUSmt0TmRx9qdhktn7ldCPmdCKyltAV6eJeceSHCTdEZAwNTmAI2sWf+SOeXyEbqlAViWWScZcrLCaW8E5CVu4KoIOw2XtqK4/4GRRSs683z5OPxuxoTht+BOTNOxifbJEP4RtJyzI27oO1rgUuqUmG4+qcTqnwpQR4=
  email:
    secure: cKTOKErgXo7WcyaqQFzBIGBpEz5X+MwtN/wHXNmLDU6BJ98IKfRcOS2oY8jG/JFoy+EQDdC8iwLfN7+z8gysMoVVbZYm/sKKLg2UXEBCe02p1mJlPDh/o/E+9ofNe1PMv/o1j4CY3YBfaVA+HB7WCGyKivu6tFgFOuoxbPdOleA=
  on:
    tags: true
notifications:
  slack:
    rooms:
    # - secure: OdYo05A7wbHvUS8VHV2ZVQ2Gjd2ubdB3ZcqaASJOxnq/JwDMJcmaT/MBOHSPA1vZe7DlXeCe20WssBEbmtoGY0out3kVdUomLge8CXf3imrKuOgg/K8zglf8g13BNHhaPqEBIa5eST0YdLxC1r0pKng+SDkOoX3xIwkCdeBKFPQ=
    - secure: gXwvemMvpSuku/2/f3sJc+z2PLhE2Srz2C9Im9jnY01W7VUgIXvu7UFeymkKi6UdF/hmsj+wCaDDXWJA8lenuGou2W/+OuP6e6Eu91hf9VqUha9Jx/5x+I8k8ThNvEp+UlWLLelftnKZK1Dus55GhPZf5CcPU+ifu85yjbXCL68=
    on_success: always
    on_pull_requests: false


# ----- Skip this until docs deploy works again ------
#- provider: script
#  skip_cleanup: true
#  script: scripts/docs-deploy.sh
#  on:
#    tags: true
#before_install:
#- openssl aes-256-cbc -K $encrypted_310f735a6883_key -iv $encrypted_310f735a6883_iv -in deploy_rsa.enc -out deploy_rsa -d
#after_install:
#- ssh-agent -k